name: aima2021
channels:
  - conda-forge
  - ankurankan
  - https://www.inf.unibz.it/~tessaris/aima-tools/conda-channel
dependencies:
  - python>=3.7
  - clingo
  - fast-downward
  - gym
  - joblib
  - jupyterlab
  - jupytext
  - matplotlib
  - nltk
  - pandas
  - pgmpy
  - pip
  - pyglet
  - python-graphviz
  - scikit-learn
  - seaborn
  - tensorflow
  - z3-solver
  - gensim
  - tensorflow
  - pip:
    - wumpus[gym] @ git+https://gitlab.inf.unibz.it/tessaris/wumpus.git@master
    - wordsegment
    - imblearn
